POST http://localhost:3502/v1.0/invoke/order-api/method/order/create HTTP/1.1
content-type: application/json

{ "id": "1e7db397-d15a-4445-bc32-a48492558eeb",
  "name"   : "John Smith",
  "sku"    : "20223",
  "price"  : 23.95,
  "shipTo" : { "name" : "Jane Smith",
               "address" : "123 Maple Street",
               "city" : "Pretendville",
               "state" : "NY",
               "zip"   : "12345" },
  "billTo" : { "name" : "John Smith",
               "address" : "123 Maple Street",
               "city" : "Pretendville",
               "state" : "NY",
               "zip"   : "12345" }
}